### ISSUE TITLE
Decide on domain

### ISSUE THREAD

**Issue by wilzbach** [libmir/website#1]
- mir.rocks
- mir.dlang.io
-...

**Comment by 9il** [comment]
mir.dlang.io for now. Can be changed is the future. I have not strong opinion about domain name

**Comment by wilzbach** [comment]
Okay [mir.dlang.io](http://mir.dlang.io) is configured & setup now.

@ others: if you have ideas for `mir.rocks` (I own the domain), don't hesitate to let me know!
