### ISSUE TITLE
Setup bot and hooks that trigger a deploy whenever the submodules are updated 

### ISSUE THREAD

**Issue by wilzbach** [libmir/website#5]
I have used this for the `dlang-tour`. The idea is very simple: it just restarts the last build on the CI provider whenever a submodule has a new commit in master.

Bot: https://github.com/dlang-tour/bot
Can be run on heroku (free!)

Hook configuration:

![image](https://cloud.githubusercontent.com/assets/4370550/23202245/6e8e8e24-f8dd-11e6-8a25-fe74f713e3a0.png)

TODO: the tour bot uses the Travis API, so we would need either need to use Travis to build & deploy or change it a bit, s.t. CircleCi is supported as well.

**Comment by 9il** [comment]
Awesome!!!

**Comment by wilzbach** [comment]
So:
- I created a new S3 bucket (and add the secret keys to the `travis.yml` here)
- I pushed the bot onto heroku and configured it
- I added a web hook to all mir repos to the bot (`https://libmir.herokuapp.com/github_hook`).

=> So whenever there's a new push on any repo, the website will automatically redeploy itself to S3 :)
The auto-deploy depends on whatever we have configured in this repo - in fact the bot will simply rerun the last successful Travis build ;-)


Please let me know in case this doesn't work, or you add a new repo.
